import random

from django.core.management.base import BaseCommand
from khodam.models import khodam


class Command(BaseCommand):
    help = 'Load khodam into the database'

    def handle(self, *args, **kwargs):
        khodam_list = [
            khodam(namaKhodam='Naga Sakti', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Ratu Pantai Selatan', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Harimau Putih', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Raja Jin', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Dewi Bulan', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Penjaga Hutan', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Singa Emas', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Banteng Sakti', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Elang Perkasa', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Laba-laba Sunda', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Buaya Hitam', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Katak Sigma', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Skibidi Sigma', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Ikan Lohan Tidak Gyat', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Burung Puyuh Warna Bjir', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Monyet Hutan', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Gajah Ngawi', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Kursi Mewing', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Balon Ku Sigma', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Di Hina Tetap Sigma', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Kue Keju', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Mobil Bekas Toyota Gyat', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Rehan Toyota', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Ikbal Hotwil', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Kuda Pake Sendal', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Sendal', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Jaket Bapak', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Kambing Hitam', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Pintu Gerbang', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Kayu Jati', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Jati Diri', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Ayam Tidak Punya KTP', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Dino Sok Inggris', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Bibir Jontor Badag', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Teh Sari Wangi', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Indomi Kecap Asin', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Burung Elang Dari Jawa', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Tidak Ada/Kosong !', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Nokia Bapak', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Telur Gulung', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Sayur Asem Kecap Manis', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Baju Terbang', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Sendal Jepit', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Nasi Padang', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Pizza Mewah', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Jus Alpukat', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Sate Ayam', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Gado-Gado', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Kambing Guling', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Tahu Bulat', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Lontong Balap', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Soto Ayam', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Bakso Gepeng', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Cilok Kenyal', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Mie Ayam Lezat', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Es Cendol Manis', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Kopi Hitam Mantap', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Brownies Lumer', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Kerak Telor', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Tempe Mendoan', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Jajanan Pasar', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Pecel Lele', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Ayam Geprek', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Roti Bakar', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Pisang Goreng', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Bubur Ayam', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Nasi Goreng Spesial', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Sop Buntut', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Gule Kambing', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Rawon Hitam', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Ikan Bakar', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Sate Kambing', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Kue Cubit', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Cakwe', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Tahu Gejrot', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Kacang Polong', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Sayur Bayam', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Sambal Terasi', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Es Dawet', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Teh Tarik', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Es Teler', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Kerupuk Kulit', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Rengginang', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Emping Melinjo', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Mie Goreng', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Risoles', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Lumpia Semarang', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Pempek Palembang', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Asinan Betawi', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Lemper Ayam', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Bika Ambon', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Klepon', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Kue Lumpur', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Putu Ayu', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Onde-Onde', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Pukis', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Serabi', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Martabak Telur', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Sempol Ayam', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Bubur Ketan Hitam', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Kai Cenat', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Ibu Kai Cenat', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Bapak Kai Cenat', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Adek Kai Cenat', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Kakak Kai Cenat', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Nenek Kai Cenat', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Kakek Kai Cenat', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Bibi Kai Cenat', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Paman Kai Cenat', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Istri Kai Cenat', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Keponakan Kai Cenat', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Bapak Nya Istri Kai Cenat', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Istri nya Bapak nya Istri Kai Cenat', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Es Dawet Ketan Hitam Pekat Oli Bekas', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Kai Cenat Mode Sigma', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Bocil Mewing', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='[Rare,Misterius,Cool,Sigma,Mewing,Made in ohio] Akbar Motor Mio Gas Elpiji Wibu Sejati Kasur Bekas Motor Supra Blukutuk-Blukutuk', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Kapten Bajak Laut Ngawi', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Mio Mirza', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Pintu Gerbang', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Kayu Jati', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Jati Diri', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Ayam Tidak Punya KTP', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Dino Sok Inggris', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Bibir Jontor Badag', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Teh Sari Wangi', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Indomi Kecap Asin', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Burung Elang Dari Jawa', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Tidak Ada/Kosong !', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Nokia Bapak', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Telur Gulung', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Sayur Asem Kecap Manis', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Baju Terbang', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Sendal Jepit', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Nasi Padang', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Pizza Mewah', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Jus Alpukat', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Sate Ayam', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Kambing Guling', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Tahu Bulat', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Lontong Balap', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Soto Ayam', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Bakso Gepeng', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Cilok Kenyal', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Mie Ayam Lezat', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Es Cendol Manis', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Kopi Hitam Mantap', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Brownies Lumer', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Kerak Telor', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Tempe Mendoan', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Jajanan Pasar', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Pecel Lele', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Ayam Geprek', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Roti Bakar', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Pisang Goreng', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Bubur Ayam', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Nasi Goreng Spesial', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Sop Buntut', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Gule Kambing', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Rawon Hitam', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Ikan Bakar', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Sate Kambing', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Kue Cubit', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Cakwe', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Tahu Gejrot', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Kacang Polong', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Sayur Bayam', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Sambal Terasi', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Es Dawet', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Teh Tarik', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Es Teler', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Kerupuk Kulit', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Rengginang', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Emping Melinjo', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Mie Goreng', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Risoles', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Lumpia Semarang', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Pempek Palembang', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Asinan Betawi', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Lemper Ayam', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Bika Ambon', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Klepon', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Kue Lumpur', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Putu Ayu', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Onde-Onde', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Pukis', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Serabi', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Martabak Telur', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Sempol Ayam', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Bubur Ketan Hitam', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Kai Cenat', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Ibu Kai Cenat', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Bapak Kai Cenat', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Adek Kai Cenat', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Kakak Kai Cenat', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Nenek Kai Cenat', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Kakek Kai Cenat', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Bibi Kai Cenat', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Paman Kai Cenat', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Istri Kai Cenat', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Keponakan Kai Cenat', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Bapak Nya Istri Kai Cenat', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Istri nya Bapak nya Istri Kai Cenat', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Es Dawet Ketan Hitam Pekat Oli Bekas', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Kai Cenat Mode Sigma', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Bocil Mewing', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='[Rare,Misterius,Cool,Sigma,Mewing,Made in ohio] Akbar Motor Mio Gas Elpiji Wibu Sejati Kasur Bekas Motor Supra Blukutuk-Blukutuk', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Kapten Bajak Laut Ngawi', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Mio Mirza', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Pintu Gerbang', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Kayu Jati', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Jati Diri', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Ayam Tidak Punya KTP', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Dino Sok Inggris', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Bibir Jontor Badag', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Teh Sari Wangi', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Indomi Kecap Asin', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Burung Elang Dari Jawa', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Tidak Ada/Kosong !', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Nokia Bapak', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Telur Gulung', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Sayur Asem Kecap Manis', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Baju Terbang', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Sendal Jepit', kekuatanKhodam=random.randint(1, 100)),
        ]
        khodam.objects.bulk_create(khodam_list)
        self.stdout.write(self.style.SUCCESS('Successfully loaded khodam'))
