import random

from django.core.management.base import BaseCommand

from khodam.models import khodam


class Command(BaseCommand):
    help = 'Load khodam into the database'

    def handle(self, *args, **kwargs):
        khodam_list = [
            khodam(namaKhodam='Naga Sakti', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Ratu Pantai Selatan', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Harimau Putih', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Raja Jin', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Dewi Bulan', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Penjaga Hutan', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Singa Emas', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Banteng Sakti', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Elang Perkasa', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Laba-laba Sunda', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Buaya Hitam', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Katak Sigma', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Skibidi Sigma', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Ikan Lohan Tidak Gyat', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Burung Puyuh Warna Bjir', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Monyet Hutan', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Gajah Ngawi', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Kursi Mewing', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Balon Ku Sigma', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Di Hina Tetap Sigma', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Kue Keju', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Mobil Bekas Toyota Gyat', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Rehan Toyota', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Ikbal Hotwil', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Kuda Pake Sendal', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Sendal', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Jaket Bapak', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Kambing Hitam', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Pintu Gerbang', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Kayu Jati', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Jati Diri', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Ayam Tidak Punya KTP', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Dino Sok Inggris', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Bibir Jontor Badag', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Indomi Kecap Asin', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Burung Elang Dari Jawa', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Tidak Ada/Kosong !', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Nokia Bapak', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Baju Terbang', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Sendal Jepit', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Es Dawet Ketan Hitam Pekat Oli Bekas', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Kai Cenat Mode Sigma', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Bocil Mewing', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='[Rare,Misterius,Cool,Sigma,Mewing,Made in ohio] Akbar Motor Mio Gas Elpiji Wibu Sejati Kasur Bekas Motor Supra Blukutuk-Blukutuk', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Kapten Bajak Laut Ngawi', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Mio Mirza', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Pintu Gerbang', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Kayu Jati', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Jati Diri', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Ayam Tidak Punya KTP', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Dino Sok Inggris', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Bibir Jontor Badag', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Teh Sari Wangi', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Indomi Kecap Asin', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Burung Elang Dari Jawa', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Tidak Ada/Kosong !', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Nokia Bapak', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Telur Gulung', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Sayur Asem Kecap Manis', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Baju Terbang', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Sendal Jepit', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Es Dawet Ketan Hitam Pekat Oli Bekas', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Kai Cenat Mode Sigma', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Bocil Mewing', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='[Rare,Misterius,Cool,Sigma,Mewing,Made in ohio] Akbar Motor Mio Gas Elpiji Wibu Sejati Kasur Bekas Motor Supra Blukutuk-Blukutuk', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Kapten Bajak Laut Ngawi', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Mio Mirza', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Pintu Gerbang', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Kayu Jati', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Jati Diri', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Ayam Tidak Punya KTP', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Dino Sok Inggris', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Bibir Jontor Badag', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Burung Elang Dari Jawa', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Tidak Ada/Kosong !', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Nokia Bapak', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Baju Terbang', kekuatanKhodam=random.randint(1, 100)),
            khodam(namaKhodam='Sendal Jepit', kekuatanKhodam=random.randint(1, 100)),
        ]
        khodam.objects.bulk_create(khodam_list)
        self.stdout.write(self.style.SUCCESS('Successfully loaded khodam'))
